sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - nvm install $NODE
  - nvm use $NODE
  - npm i -g npm@^3.3.0
before_script:
  - npm prune
script: npm run $COMMAND
after_success:
  - if [[ $COMMAND = test:coverage ]]; then npm run test:coverage:upload; fi
  - npm run build
  - npm run semantic-release
env:
  matrix:
  # blocked by https://github.com/semantic-release/semantic-release/pull/90
  # - NODE=0.10 COMMAND=test
  # - NODE=4 COMMAND=test:coverage
  - NODE=4 COMMAND=test
